spring:
  application:
    name: account

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
server:
  port: 20261
eureka:
  instance:
    prefer-ip-address: true