spring:
  application:
    name: account

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:16168/db_account
    username: itpusr
    password: itp@168
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false


server:
  port: 20261
eureka:
  instance:
    prefer-ip-address: true

axon:
  axonserver:
    enabled: false
  kafka:
    bootstrap-servers: localhost:29092,localhost:29094,localhost:29096
    default-topic: Axon.AccountCQRS.Events
    client-id: kafka-axon-account
    message-converter-mode: default
    properties:
      security.protocol: PLAINTEXT
    publisher:
      confirmation-mode: transactional
    producer:
      transaction-id-prefix: kafka-axon-
      retries: 5
      event-processor-mode: tracking
  serializer:
    general: jackson
    events: jackson
    messages: jackson